# (C) Copyright 2019-2021 Hewlett Packard Enterprise Development LP

# Configuration to deploy the Cloud Volumes Container Storage Provider
# Kubernetes = v1.15
#
# example usage: kubectl create -f <this_file>

---

#################### CSP Deployment ####################
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cv-csp
  namespace: hpe-storage
spec:
  selector:
    matchLabels:
      app: cv-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: cv-csp
    spec:
      priorityClassName: system-cluster-critical
      serviceAccount: hpe-csi-controller-sa
      containers:
        - name: cv-csp
          image: quay.io/hpestorage/cv-csp:edge
          imagePullPolicy: Always
          env:
          - name: API_HOST
            value: "https://prod.cloudvolumes.hpe.com"
          ports:
          - containerPort: 8080

---

#################### CSP Service ####################
kind: Service
apiVersion: v1
metadata:
  name: cv-csp-svc
  namespace: hpe-storage
  labels:
    app: cv-csp-svc
spec:
  selector:
    app: cv-csp
  ports:
  - name: service-port
    port: 8080
    targetPort: 8080
